feat: Add imoji to align with_friend text with top text
techinpark/Jandi pull request #20
Opened 2022-04-19 11:52 UTC by stomx

2022-04-21 11:16 UTC, stomx commented
Please check this request

2022-04-30 04:18 UTC, techinpark requested changes

2022-04-30 04:18 UTC, techinpark commented on Supporting FIles/ko.lproj/Localizable.strings
>  "with_friend" = "\n @${username}와 함께";
Do you mind if I don't erase that line?

2022-04-30 04:18 UTC, techinpark commented on Supporting FIles/ko.lproj/Localizable.strings
>  "with_friend" = "\n @${username}와 함께";
I think `with_friend` key is duplicated

2022-04-30 04:18 UTC, techinpark commented on Supporting FIles/ko.lproj/Localizable.strings
>  "with_friend" = "\n @${username}와 함께";
@stomx

2022-08-03 18:46 UTC, closed without merging