✨ Add a feature showing friend's commits
techinpark/Jandi pull request #6
Opened 2021-02-21 10:07 UTC by dannyhann

친구의 Github 아이디를 입력하면
친구의 Commit 횟수를 같이 표현하는 기능을 추가하였습니다.

2021-02-21 10:09 UTC, dannyhann commented
<img width="292" alt="스크린샷 2021-02-21 오후 7 07 43" src="https://user-images.githubusercontent.com/6360420/108621801-350eec00-7478-11eb-8697-51a2148d6676.png">

2021-02-21 14:37 UTC, techinpark requested changes
@dannyhann 좋은 기능 추가해주셔서 감사합니다. 몇가지 코멘트 달았습니다! 

개발과는 별개로, 몇가지 의견 나누고 싶은 부분이 있습니다. 

1. 친구의 아이디가 추가되지 않은 상태에서도 `친구 아이디 변경` 이라고 노출되는 메뉴를 아래와 같이 변경하는것이 어떨까 싶습니다. 
```
- 친구의 아이디가 추가되지 않은 경우 : 친구 아이디 추가 
- 친구의 아이디가 추가되어 있는 경우 : 친구 아이디 변경 
```
2. 친구 아이디가 추가되어 있는 경우, 텍스트의 색상이 나의 커밋 카운트에 따라 표시되어지는데 이부분도 각각 분리가 가능하다면 분리해서 색상이 표시되면 좋을것 같습니다

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +}
더 좋은방법으로 개선 해주셔서 감사합니다. 
해당 클래스를 별도의 파일로 관리하는건 어떨까요? 
`Sources/Model/ContributteData.swift` 파일을 별도로 생성해서 분리하는것도 좋을 것 같습니다!

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +class ContributeData{
```suggestion 
class ContributeData {
```
공백 하나 추가되면 좋을 것 같습니다.

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +    let weekend, date : String
```swift 
let weekend: String
let data: String
```

저는 보통 모든 변수의 자료형을 적는것을 더 좋아하는데 이유는 좀더 명시적이기 때문입니다

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +    private var myContributes: [ContributeData] = [];
불필요한 `;` 세미콜론 제거가 필요해보입니다.

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +            guard let friendLastContribute = self.friendContributes.last else {return}
```suggestion
guard let myLastContribute = self.myContributes.last else { return }
guard let friendLastContribute = self.friendContributes.last else { return }
```

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +            for myContribute in self.myContributes{
```suggestion
            for myContribute in self.myContributes {
```

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +        guard let targetURL = URL(string: "https://github.com/users/\(username)/contributions") else {return}
```suggestion 
        guard let targetURL = URL(string: "https://github.com/users/\(username)/contributions") else { return }
```

2021-02-21 14:37 UTC, techinpark commented on Sources/AppDelegate.swift
> +        guard let attr = ele.getAttributes() else {return ContributeData(count: 0, weekend: "", date: "")}
```suggestion 
        guard let attr = ele.getAttributes() else { return ContributeData(count: 0, weekend: "", date: "") }
```

2021-02-22 10:34 UTC, dannyhann commented
의견 주신 내용과 리뷰해주신 부분 반영하였습니다. 🌱  @techinpark

2021-02-22 13:50 UTC, techinpark approved these changes
수고 많으셨습니다 기여에 감사드립니다 😄 

Thanks for your contributions!

2021-02-22 13:51 UTC, merged